#!/bin/sh

set -eux

[ "${VENDOR:-}" -a "${PROJECT:-}" ] || { echo missing VENDOR/PROJECT environment variables; exit 1; }

. /etc/os-release
[ "${VERSION:-}" ] || EXPERIMENTAL=1

: ${REPO:=https://github.com/FreeRADIUS/freeradius-server.git}
: ${BRANCH:=v3.0.x}
: ${TAG:=v3.0.x}

. /etc/environment
export https_proxy http_proxy ftp_proxy

export DEBIAN_FRONTEND=noninteractive

{
	echo tzdata tzdata/Areas select Etc;
	echo tzdata tzdata/Zones/Etc select UTC;
} | debconf-set-selections

apt-get update
apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
		--option=Dpkg::options::=--force-unsafe-io install --no-install-recommends \
	auto-apt-proxy \
	eatmydata

[ ! "${APT_PROXY:-}" ] || printf "%s\tapt-proxy\n" "$APT_PROXY" >> /etc/hosts

export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libeatmydata.so

#apt-get update
apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
		--option=Dpkg::options::=--force-unsafe-io --no-install-recommends upgrade
apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
		--option=Dpkg::options::=--force-unsafe-io install --no-install-recommends \
	autoconf \
	automake \
	${OPENSSL:+bc} \
	build-essential \
	ca-certificates \
	cmake \
	curl \
	dbus \
	debhelper \
	default-libmysqlclient-dev \
	dpkg-dev \
	systemd \
	fakeroot \
	freetds-dev \
	git \
	hostapd \
	iproute2 \
	nftables \
	libcap-dev \
	libcurl4-openssl-dev \
	libdbus-1-dev \
	libgdbm-dev \
	libhiredis-dev \
	libiodbc2-dev \
	libjson-c-dev \
	libkrb5-dev \
	libldap2-dev \
	libmemcached-dev \
	libnl-3-dev \
	libnl-genl-3-dev \
	libnl-route-3-dev \
	libpam0g-dev \
	libpcap-dev \
	libperl-dev \
	libpq-dev \
	libreadline-dev \
	libsasl2-dev \
	libsqlite3-dev \
	libssl-dev${EXPERIMENTAL:+/experimental} \
	libsystemd-dev \
	libtalloc-dev \
	libtool \
	libwbclient-dev \
	libykclient-dev \
	libyubikey-dev \
	make \
	openssl \
	pkg-config \
	python2-dev \
	python3-dev \
	quilt \
	samba-dev \
	ssl-cert \
	systemd-sysv \
	tcpdump \
	udhcpd

apt-get -y autoremove
apt-get clean
find /var/lib/apt/lists -type f -delete

case "${PACKER_BUILDER_TYPE:-}" in
docker)
	# running systemd in a container
	rm -f /usr/sbin/policy-rc.d

	# disable harmless error
	systemctl mask dev-hugepages.mount
esac

if [ -d /opt/$VENDOR/$PROJECT ]; then
	git -C /opt/$VENDOR/$PROJECT reset --hard
	git -C /opt/$VENDOR/$PROJECT pull origin HEAD
else
	mkdir /opt/$VENDOR
	git clone /tmp/$VENDOR-$PROJECT.git /opt/$VENDOR/$PROJECT
fi

shred -u /tmp/$VENDOR-$PROJECT.git

if [ "${OPENSSL:-}" ]; then
	mkdir -p /usr/src/openssl
	cd /usr/src/openssl
	curl -f \
		-L -O -J http://deb.debian.org/debian/pool/main/o/openssl/openssl_${OPENSSL}-1.dsc \
		-L -O -J http://deb.debian.org/debian/pool/main/o/openssl/openssl_${OPENSSL}.orig.tar.gz \
		-L -O -J http://deb.debian.org/debian/pool/main/o/openssl/openssl_${OPENSSL}.orig.tar.gz.asc \
		-L -O -J http://deb.debian.org/debian/pool/main/o/openssl/openssl_${OPENSSL}-1.debian.tar.xz
	dpkg-source -x openssl_${OPENSSL}-1.dsc
	cd openssl-${OPENSSL}
	sed -i.bak -e 's/ -fzero-call-used-regs=used-gpr//' debian/patches/debian-targets.patch Configurations/20-debian.conf
	dpkg-source --commit . x-interop-trim-flag </dev/null
	env DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -rfakeroot -us -uc
	dpkg -i ../libssl3_3.0.2-1_amd64.deb ../openssl_3.0.2-1_amd64.deb ../libssl-dev_3.0.2-1_amd64.deb
fi

(
	set -eu
	cd /usr/src
	# https://github.com/jimdigriz/freeradius-oauth2-perl#8021x-1
	if [ -d hostap ]; then
		cd hostap
		git reset --hard
		git pull
	else
		git clone --single-branch --branch main https://w1.fi/hostap.git
		cd hostap
	fi
	git checkout hostap_2_10

	sed -e 's/^#CONFIG_EAPOL_TEST=y/CONFIG_EAPOL_TEST=y/; $a\CFLAGS += -Wno-error=deprecated-declarations' wpa_supplicant/defconfig > wpa_supplicant/.config
	make -C wpa_supplicant -j$(($(getconf _NPROCESSORS_ONLN)+1)) eapol_test
	ln -f -s -t /usr/local/bin $(pwd)/wpa_supplicant/eapol_test
)
(
	set -eu
	cd /usr/src
	if [ -d freeradius-server ]; then
		cd freeradius-server
		quilt pop -a || true
		git reset --hard
		git pull
	else
		git clone --single-branch --branch $BRANCH $REPO
		cd freeradius-server
		git checkout $TAG
	fi
	# FR build is racey on Debian parallel builds :(
	make deb
	#fakeroot debian/rules debian/control
	#fakeroot dpkg-buildpackage -b -uc -jauto

	# make testing faster
	curl -f --compressed -o raddb/certs/dh https://ssl-config.mozilla.org/ffdhe2048.txt

	make test

	# make installation faster
	mkdir -p /etc/freeradius/certs
	ln -f -t /etc/freeradius/certs raddb/certs/dh

	find /usr/src \
			-maxdepth 1 -type f \
			-regex '.*/\(freeradius_\|libfreeradius3_\|freeradius-\(common\|config\|utils\)\).*\.deb' \
		| xargs -t apt-get -y install

	mkdir -p /var/log/freeradius/tlscache
	chown root:freerad /var/log/freeradius/tlscache
	chmod 770 /var/log/freeradius/tlscache

	ln -f -s -t /opt/$VENDOR/$PROJECT /etc/freeradius/certs
)

find /etc/freeradius/mods-enabled /etc/freeradius/sites-enabled -type f,l -delete
find /etc/freeradius/sites-enabled -type f,l -delete
find /opt/$VENDOR/$PROJECT/services/freeradius/policy.d -type f			| xargs -r -t ln -f -s -t /etc/freeradius/policy.d
find /opt/$VENDOR/$PROJECT/services/freeradius/mods-available -type f,l		| xargs -r -t ln -f -s -t /etc/freeradius/mods-enabled
find /opt/$VENDOR/$PROJECT/services/freeradius/sites-available -type f,l	| xargs -r -t ln -f -s -t /etc/freeradius/sites-enabled

freeradius -C || freeradius -XC
if [ "${PACKER_BUILDER_TYPE:-}" = null ]; then
	invoke-rc.d freeradius start
	invoke-rc.d freeradius reload
fi

ln -f -s /opt/$VENDOR/$PROJECT/services/nftables.conf /etc/nftables.conf
systemctl enable nftables.service

ln -f -s /opt/$VENDOR/$PROJECT/services/udhcpd.conf /etc/udhcpd.conf

find /opt/$VENDOR/$PROJECT/services/systemd -type f | xargs ln -f -s -t /lib/systemd/system
ls /opt/$VENDOR/$PROJECT/services/systemd | xargs systemctl enable

ln -f -s /opt/$VENDOR/$PROJECT/services/hostapd.conf /etc/hostapd/hostapd.conf
systemctl unmask hostapd.service
systemctl enable hostapd.service

[ "${PACKER_BUILDER_TYPE:-}" = docker ] || sed -i -e '/apt-proxy/ d' /etc/hosts
unset LD_PRELOAD
sync

exit 0
